apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tas-grafana-route
  namespace: trusted-artifact-signer
spec:
  to:
    kind: Service
    name: tas-grafana-service
    weight: 100
  port:
    targetPort: grafana
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None