apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-reader
  namespace: trusted-artifact-signer
  labels:
    app: tas-monitoring
    component: grafana
  annotations:
    description: "ServiceAccount for TAS Grafana to access Prometheus metrics" 
    managed-by: "tas-monitoring-stack"
automountServiceAccountToken: true